/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAppointmentsRouteImport } from './routes/app/appointments'
import { Route as AppCheckInsRouteImport } from './routes/app/check-ins'
import { Route as AppHabitsRouteImport } from './routes/app/habits'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppPlanRouteImport } from './routes/app/plan'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as AppResourcesRouteImport } from './routes/app/resources'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesSlugRouteImport } from './routes/stories/$slug'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAppointmentsRouteImport } from './routes/studio/appointments'
import { Route as StudioCheckInsRouteImport } from './routes/studio/check-ins'
import { Route as StudioMessagesRouteImport } from './routes/studio/messages'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as StudioClientsIndexRouteImport } from './routes/studio/clients/index'
import { Route as StudioClientsIdRouteImport } from './routes/studio/clients/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCheckInsRoute = AppCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRouteRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioAppointmentsRoute = StudioAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioCheckInsRoute = StudioCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioMessagesRoute = StudioMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudioRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioClientsIndexRoute = StudioClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioClientsIdRoute = StudioClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => StudioRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/assess': typeof AssessRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/check-ins': typeof AppCheckInsRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/plan': typeof AppPlanRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/resources': typeof AppResourcesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/studio/appointments': typeof StudioAppointmentsRoute
  '/studio/check-ins': typeof StudioCheckInsRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/app/': typeof AppIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
  '/studio/clients/': typeof StudioClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assess': typeof AssessRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/check-ins': typeof AppCheckInsRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/plan': typeof AppPlanRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/resources': typeof AppResourcesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/studio/appointments': typeof StudioAppointmentsRoute
  '/studio/check-ins': typeof StudioCheckInsRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/app': typeof AppIndexRoute
  '/journal': typeof JournalIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
  '/studio/clients': typeof StudioClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/assess': typeof AssessRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/check-ins': typeof AppCheckInsRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/plan': typeof AppPlanRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/resources': typeof AppResourcesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/studio/appointments': typeof StudioAppointmentsRoute
  '/studio/check-ins': typeof StudioCheckInsRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/app/': typeof AppIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
  '/studio/clients/': typeof StudioClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/studio'
    | '/about'
    | '/assess'
    | '/book'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/app/appointments'
    | '/app/check-ins'
    | '/app/habits'
    | '/app/messages'
    | '/app/plan'
    | '/app/profile'
    | '/app/progress'
    | '/app/resources'
    | '/journal/$slug'
    | '/programs/$slug'
    | '/stories/$slug'
    | '/studio/appointments'
    | '/studio/check-ins'
    | '/studio/messages'
    | '/app/'
    | '/journal/'
    | '/programs/'
    | '/stories/'
    | '/studio/'
    | '/api/auth/$'
    | '/studio/clients/$id'
    | '/studio/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assess'
    | '/book'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/app/appointments'
    | '/app/check-ins'
    | '/app/habits'
    | '/app/messages'
    | '/app/plan'
    | '/app/profile'
    | '/app/progress'
    | '/app/resources'
    | '/journal/$slug'
    | '/programs/$slug'
    | '/stories/$slug'
    | '/studio/appointments'
    | '/studio/check-ins'
    | '/studio/messages'
    | '/app'
    | '/journal'
    | '/programs'
    | '/stories'
    | '/studio'
    | '/api/auth/$'
    | '/studio/clients/$id'
    | '/studio/clients'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/studio'
    | '/about'
    | '/assess'
    | '/book'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/app/appointments'
    | '/app/check-ins'
    | '/app/habits'
    | '/app/messages'
    | '/app/plan'
    | '/app/profile'
    | '/app/progress'
    | '/app/resources'
    | '/journal/$slug'
    | '/programs/$slug'
    | '/stories/$slug'
    | '/studio/appointments'
    | '/studio/check-ins'
    | '/studio/messages'
    | '/app/'
    | '/journal/'
    | '/programs/'
    | '/stories/'
    | '/studio/'
    | '/api/auth/$'
    | '/studio/clients/$id'
    | '/studio/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssessRoute: typeof AssessRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/check-ins': {
      id: '/app/check-ins'
      path: '/check-ins'
      fullPath: '/app/check-ins'
      preLoaderRoute: typeof AppCheckInsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/habits': {
      id: '/app/habits'
      path: '/habits'
      fullPath: '/app/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/appointments': {
      id: '/studio/appointments'
      path: '/appointments'
      fullPath: '/studio/appointments'
      preLoaderRoute: typeof StudioAppointmentsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/check-ins': {
      id: '/studio/check-ins'
      path: '/check-ins'
      fullPath: '/studio/check-ins'
      preLoaderRoute: typeof StudioCheckInsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/messages': {
      id: '/studio/messages'
      path: '/messages'
      fullPath: '/studio/messages'
      preLoaderRoute: typeof StudioMessagesRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/clients/': {
      id: '/studio/clients/'
      path: '/clients'
      fullPath: '/studio/clients/'
      preLoaderRoute: typeof StudioClientsIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/clients/$id': {
      id: '/studio/clients/$id'
      path: '/clients/$id'
      fullPath: '/studio/clients/$id'
      preLoaderRoute: typeof StudioClientsIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppCheckInsRoute: typeof AppCheckInsRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppCheckInsRoute: AppCheckInsRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPlanRoute: AppPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface StudioRouteRouteChildren {
  StudioAppointmentsRoute: typeof StudioAppointmentsRoute
  StudioCheckInsRoute: typeof StudioCheckInsRoute
  StudioMessagesRoute: typeof StudioMessagesRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioClientsIdRoute: typeof StudioClientsIdRoute
  StudioClientsIndexRoute: typeof StudioClientsIndexRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioAppointmentsRoute: StudioAppointmentsRoute,
  StudioCheckInsRoute: StudioCheckInsRoute,
  StudioMessagesRoute: StudioMessagesRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioClientsIdRoute: StudioClientsIdRoute,
  StudioClientsIndexRoute: StudioClientsIndexRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AssessRoute: AssessRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
